version: '3.4'

services:
  dockersqlasp:
    image: ${DOCKER_REGISTRY-}dockersqlasp
    build:
      context: .
      dockerfile: DockerSqlAsp/Dockerfile
  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=LD52N2i7!WjOcuX~orSEy6
      - ACCEPT_EULA=Y
    ports:
      - "1440:1433"